# Generated by Django 2.2.10 on 2020-03-30 13:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
