# Generated by Django 2.2.10 on 2020-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albumi',
            fields=[
                ('albumi_id', models.AutoField(primary_key=True, serialize=False)),
                ('albumi_artisti', models.CharField(max_length=250)),
                ('albumi_nimi', models.CharField(max_length=250)),
                ('albumi_vuosi', models.CharField(max_length=250)),
            ],
        ),
    ]
